version: '3.4'
services:
    looper:
        build:
            context: .
        command:
            "/bin/bash -c 'while true; do sleep 1; done'"
        volumes:
            - ./:/app
        ports:
            - "9000:9000"
